### ISSUE TITLE
Dbjoin multiselect: dbjoin values are overridden if user has no edit access

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1316]
http://www.fabrikar.com/forums/index.php?threads/wrong-value-in-databasejoin-field-multi-dropdown-on-save.39444/
Setup: dbjoin multiselect, add/edit access=admin, details=public
Admin sets some values
User edits the record (dbjoin is showing readonly)

After form submit the records in table_repeat_dbjoin are still there but the dbjoin values are overridden with the last n table_repeat_dbjoin.ids (n= number of selected dbjoin optioins)

**Comment by trob** [comment]
Seems to be the same here
http://www.fabrikar.com/forums/index.php?threads/bug-introduced-in-recent-github.40321/

**Comment by cheesegrits** [comment]
OK, I can see what's happening, but still trying to find a fix.

NOTES TO SELF ..

In the form view's _cryptViewOnlyElements(), where we pick up the values for read only elements so we can encrypt them in the hidden fabrik_vars[] form field, we are getting the _ids rather than the _raws for the multiselect.  Those get sorted out for display in the databajoin.php model, inside render().  But that just changes the displayed values.

I think what we need to fix is getValuesToEncrypt(), called form the form models groupView().

**Comment by cheesegrits** [comment]
Should be fixed in https://github.com/Fabrik/fabrik/commit/c181b8076c1df10d8ab559774f66019f0e5150d5
