### ISSUE TITLE
Fabrik and his Require.js create problems for all jquery based modules in every Joomla template

### ISSUE THREAD

**Issue by simbus82** [Fabrik/fabrik#1393]
Today, github of this morning, there is no chanche to have in the same page the universal, ultra stable and iper used "unite revolution slider" (based on worldwide themepunch's revolution slider).

I load a module with a fabrik simple form in the same page, with name, email and "send" button. Require.js simply kill my slideshow.

With Magebridge, fabrik kill al js inclusion's system.
With every extensions that have some jquery or js functions.... Fabrik kill everyone.

We have to use fabrik... only with fabrik.... It is very bad... 
Please release a version without require.js!!!!

**Comment by cheesegrits** [comment]
We are testing a fix for that now.

**Comment by britzke** [comment]
I agee with it. I have had problems with require.js in conjunction with other extension/templates, too.

burghard@iSir

**Comment by cheesegrits** [comment]
Can you test the latest github?  I can't test against that slider extension @simbus82 mentioned , as it's a paid app.  But I've tested against some other things that had the same 'mismatched anonymous define' issue, like WidgetKit, and those are now fixed.

**Comment by simbus82** [comment]
it seems working now :100: 
I apologize for the tone of my bug report: i know that require.js is good for performance, but i think we need to calculate very well if the cost for performance can take over compatibility.

**Comment by Sophist-UK** [comment]
@simbus82 - I am speaking up here as someone independent as I know that both Hugh and Rob would be too tactful to say this.

I do hope that you appreciate just how quickly Hugh responded to your issue report. This is the sort of instant support that with a large software house you would need to pay $000s per month for.

Since you didn't provide any links to where you might have raised this issue elsewhere, such as in the forums, I can only assume that this was your first report of this issue, so I do hope that you appreciate just how inappropriate it was to be so rude when you were only just raising the issue for the first time.

However I am sure that Hugh appreciates your apology about it.

P.S. Fabrik is not the quickest development environment, but it is definitely the most capable. Hugh and Rob have sweated for years to create this (with a bit of help on occasions from users like me, Troester etc.) So please don't call working with Fabrik "a real pain" - it is pretty ungrateful considering you are getting all its functionality for free.

**Comment by simbus82** [comment]
Contextualize my words Sophie please. :-(
"Joomla 3.x + Yireo Magebridge + Magento 1.9.x, where creating form with Fabrik is a real pain".
I have wrote in forum for more than one year about mootools and for the problem with requie.js (never had problems before introduction of require.js some times ago... )
http://liquid.fabrikar.com/forums/index.php?members/simbus82.48129/recent-content

**Comment by Sophist-UK** [comment]
No - you last posted in July 2014 in the forums, and you didn't link to it here - so I could not contextualise.

I don't know why Hugh didn't look into the JS errors you were reporting and create this fix then, but he didn't - and you didn't pursue it there, and suddenly create a pretty rude issue here without explaining any history. I was shocked at your tone. No excuses please.

**Comment by cheesegrits** [comment]
@simbus82 there are always compatibility issues when coding extensions for a product like Joomla, where a lot of people have to play nicely together in the same sandbox.  I can't remember a time where there hasn't been some major compatibility issue going on - like version clashes of Mootools back before JS started shipping a standard version.  Then people loading jQuery without compat mode, and clashing versions of jQuery.  Now it's templates using Bootstrap v3 when JS is still "standardised" on v2, causing people like us huge headaches.

The "mismatched anonymous define" thing is just another example.  Technically, it's not require.js doing things wrong, it's the modules it is clashing with which are being a bit lazy, making assumptions about the environment they will be running in, and causing the problems.  But of course being technically in the right doesn't help.

Joomla is a fine balancing act between providing a stable, reliable platform, and keeping up with the rapidly changing world of web technology.  Right now, one thing it lacks is an overall Javascript dependency management system, which is why we use require.js.  It's not a "performance" issue, it's simply the only way to manage something as large and dynamic as Fabrik, where the JS being loaded on any given page can vary so tremendously, and the logic for how the file loading has to be ordered, and what depends on what (literally billions of possible permutations) becomes impossible to manage by hand.

As soon as Joomla adopts a strategy for dependency management, we'll use it - be it require.js, or something else.  Until then, any such system we use will have compatibility issues with some of the thousands of plugins out there, and all we can do is respond to issues, and fix them in a timely fashion.

**Comment by cheesegrits** [comment]
Oh, and just for the record, yes, I was a little put off by the tone of the post.  When someone describes the product you have poured years of your life into as a "cancer", when opening the first bug report on a solvable issue ... it is hurtful.

I understand how frustrating it can be, dealing with Javascript compatibility issues in Joomla, as I have to deal with them every day.  But in general, if you are reporting an issue with free software and asking someone to fix it for you, it doesn't hurt to be polite.

   -- hugh

**Comment by cheesegrits** [comment]
Re the forum posts - as it says in the description for the Community forum, staff do not monitor it.  It is for Community support.  We scan it for serious issues, and help out if we can, or if we see a pattern of multiple reports of the same issue ... but if people need direct support for issues affecting them, we have a subscription support system.  The software is free, but an unfortunate fact of life is that the authors of the software need to pay rent, keep the lights on, and put food on the table.

With this issue, we started to see recurring reports, especially from WidgetKit users, so we began looking for potential solutions a few months ago.  We still don't have a 100% reliable fix, but the update we did today should resolve most usage cases.

Anyway, problem hopefully solved, discussion over.

**Comment by simbus82** [comment]
Require.js, i spoke about require.js @cheesegrits O_o
I can't think nothing negative about Fabrik itself, by the way is one of the most live joomla extension on github.
Fabrik for me is the first extension that i put in our joomla "package" for our customer. The problem starts when require.js is introduced some times ago... Compatibility is gone for a lot of extensions. In next days we will reopen a subscription for support in Fabrikar (we have on old work account expired some times before the release of Fabrik 3.1, not renewed after the transition to J3), first for reward your work, and then for let the forum takes trace about this type of problems.

**Comment by Sophist-UK** [comment]
Actually, @simbus82 is a professional web development organisation (see http://www.simbus82.net/), and if they are delivering web sites to their customers using Fabrik you might think it would make sense for them to pay for support so that they can provide the best possible service to their customers, especially since their customers presumably pay them for support. Seems like a false economy to me.

@simbus82 - since your customers have had problems for 8 months that would have been solved had you taken out a Professional Support subscription with Fabrikar, are you now going to recognise the value that Rob and Hugh provide by taking out a Professional Subscription?

**Comment by simbus82** [comment]
@Sophist-UK Do you think i can open a support subscription after this statements?
http://fabrikar.com/forums/index.php?threads/javascript-errors-and-conflicts-with-fabrik-3-1-1-git.38846/#post-195359
http://fabrikar.com/forums/index.php?threads/javascript-errors-and-conflicts-with-fabrik-3-1-1-git.38846/#post-195486

If a developer says me that some things can't be "changed" until a new version, obviously i understand that even with a paid subscription i can't request nothing about changing how things works.

**Comment by Sophist-UK** [comment]
@simbus82 That's a pretty feeble excuse. You were getting specific javascript errors, and Hugh would have looked at them if you had a paid subscription. Instead because your didn't want to spend any of the money you were receiving from your customers for providing support with Fabrikar, your customers suffered ongoing issues which Hugh could have solved for you.

Don't blame Fabrikar staff because you are a cheapskate.

**Comment by cheesegrits** [comment]
OK, let's all take a time out.  I really don't want to have a food fight on
github.

**Comment by simbus82** [comment]
Ok you are right @cheesegrits. Ehm today i have paid a standard subscription, but i have not received accesses (i can't login with new paid account) or receipt from Fabrikar, i have wrote in Contact Us (with a check in "send me a copy") and i have not received nothing: maybe some email problems? Thanks.

**Comment by trob** [comment]
" i have paid a standard subscription, but i have not received accesses "
did you try to log out - clear browser cache - log in again?

**Comment by simbus82** [comment]
Yes @trob, i have removed all cookies too, when i log in i receive this error
"Master User Authentication Failed". Lost Password request didn't send me nothing, and i have not received nothing about payment that i do this morning. Ehm, here we are a little OT about this...

**Comment by trob** [comment]
Did you upgrade your existing account?
or added a new one (if yes, which username?)

**Comment by pollen8** [comment]
@simbus82  which user name did you create the subscription with? I don't see one listed on your simbus82 account

**Comment by pollen8** [comment]
if it was with simbus82, then could you post the paypal email address you used to sign up with

**Comment by simbus82** [comment]
A new account with username "quantility", i write it in fabrikar.com contact us form

**Comment by Sophist-UK** [comment]
This thread keeps getting more and more entertaining.

Apparently High / Rob are now expected to be psychic and don't need to receive obvious information like the new userid.

**Comment by pollen8** [comment]
HI the user 'quantility' was not active, I couldn't see why that would be. I've activated it so you should be able to log in now.

**Comment by simbus82** [comment]
@pollen8 I can not access even now :-( 

If i login in Fabrikar.com frontend i receive this error:
```
"Master User Authentication Failed"
```

I have tried to login with username or with a complete email in forum:
```
Fabrik
Server Error
Undefined index: salt
XenForo_Application::handlePhpError() in XenForo/Authentication/Core.php at line 109
XenForo_Authentication_Core->authenticate() in XenForo/Model/User.php at line 1041
XenForo_Model_User->validateAuthentication() in XenForo/ControllerPublic/Login.php at line 79
XenForo_ControllerPublic_Login->actionLogin() in XenForo/FrontController.php at line 313
XenForo_FrontController->dispatch() in XenForo/FrontController.php at line 132
XenForo_FrontController->run() in /home/fabrikar/public_html/forums/index.php at line 13
```

@Sophist-UK @pollen8 I have tried to contact you here http://fabrikar.com/contact-us with the checkbox "Send me a copy", i don't have received nothing. It may be that form is broken?

Then i tried password recovery and username remember: i have write the right email address, fabrikar.com show me the joomla system message with a positive "email sent" information. But i have not received any email.
Can you check if fabrikar.com site have some problems about email sending or account generating?

@Sophist-UK Hours ago I have used all contact methods in the site for not write here sensible data... a part the forum where i not see a clear section for starting a thread about "site". If you can help, thank you in advance.

**Comment by Sophist-UK** [comment]
I can't help you with this - I am only a community user like you used to be.

This is not anything Hugh and Rob have done deliberately - its a bug, and they are working on it. So keep it polite, keep using Github to tell them what you are seeing, and they will continue trying to fix it for you.

**Comment by simbus82** [comment]
Obviously @Sophist-UK, i have never thinked is other than a bug! I try to report the problems, but sometimes the pressure put by my work makes me to write a bit roughly.
So is it right to continue this in Github? Or do you prefer that i open a thread in forum? Thanks.

**Comment by trob** [comment]
So can you log in now?

**Comment by simbus82** [comment]
No @trob, i receive always this error:

"Master User Authentication Failed"

**Comment by Sophist-UK** [comment]
Well good luck posting in the forum then if you are unable to login.

**Comment by cheesegrits** [comment]
We get that error sometimes when an account gets activated, it's an issue with the JFusion / XenForo bridge I've been trying to track down for a while.  I'll go fix the account now.

**Comment by cheesegrits** [comment]
OK, you should have mail from me (on the email associated with that account) with a new password, which should fix that authentication problem.

**Comment by cheesegrits** [comment]
Just FYI, I found an issue with the requirejs fix from last night (only affecting the backend) and committed another fix today.

**Comment by simbus82** [comment]
@cheesegrits thank thank you! Now i can login with the account with subscription :-)
PS: it seems that now require.js is more and more compatible with other javascript frameworks in Joomla. We have a "made from scratch" template framework, but its "head" is a clone of Joomla Protostar, so we load javascripts in same manner to not have errors for who develop extensions testing on default templates. Nice to see that now works so good! Thanks!

**Comment by cheesegrits** [comment]
Good, I'm glad it's working out.  No doubt there will still be some plugins
that still conflict, but things are lot better now.

**Comment by Pakeydev** [comment]
Hi,
Can the free account post to forum? If yes then I think I have the same login problem. Click the forgot password but did not receive any email. It's a new account and try to login since 1-2 weeks ago.

See attached file;
![error](https://cloud.githubusercontent.com/assets/12601807/7802825/fb6fc808-0370-11e5-889f-fba497bad3e1.png)

**Comment by Sophist-UK** [comment]
Emails do not seem to be working - I requested userid / password details emails and they never arrived.

**Comment by cheesegrits** [comment]
Working on it now

**Comment by cheesegrits** [comment]
This should be fixed.  Seems that the subnet we are on had gotten RBL'ed by some of the big anti-spam sites (like Barracuda), due to activity from other domains hosted by the same provider.

I've now switched all of our outbound mail to use Mandrill, which should prevent this kind of thing in the future.

   -- hugh
