### ISSUE TITLE
35 - missing files?

### ISSUE THREAD

**Issue by jaanusnurmoja** [Fabrik/fabrik#1487]
Fabrik 3.5 - when trying to open the main Fabrik page in admin:
Warning: require(/home/.../administrator/components/com_fabrik/models/controller.php): failed to open stream: No such file or directory in /home/.../components/com_fabrik/autoloader.php on line 86 Fatal error: require(): Failed opening required '/home/.../administrator/components/com_fabrik/models/controller.php' (include_path='.:/usr/local/php55/lib/php') in /home/.../components/com_fabrik/autoloader.php on line 86

**Comment by bauer-git** [comment]
I have over a hundred fabrik github archives on my PC since January 2014.
The last archive I can find where this file was included in administrator/components/com_fabrik/fabrik.xml was 01/27/2014 (and even in that zip the controller.php file itself is nowhere to be found). 

So it must have been a bug that was fixed (removed from the fabrik.xml) between 01/27/2014 and 01/30/2014 (the date of the next archive I have). Yet somehow it got re-introduced into the fabrik.xml file in the last github update.

**Comment by trob** [comment]
I can't find any file autoloader.php anywhere in my fabrik (nor Fabrik2, Fabrik3.0, Fabrik3.2), only in akeeba - which is doing things like require...

No idea where this may come from.
Is this the same site which was running the Fabrik upgrade script (with error ... unknown column something..) on install or update?

**Comment by jaanusnurmoja** [comment]
It's Fabrik 3.5 that I tried to test :) As you see in title

2015-05-10 18:42 GMT+03:00 troester <notifications@github.com>:

**Comment by pollen8** [comment]
3.5 isn't ready for any type of testing yet - I'm still refactoring it. I'll let people know when its in a state where it can be tested

**Comment by jaanusnurmoja** [comment]
ok, will wait

**Comment by bauer-git** [comment]
I'm sorry - the whole 3.5 thing went right over my head.
The only file I checked for was controller.php - and that is the one that was removed from fabrik.xml since 01/27/2014 and is back in the fabrik.xml file as of the latest github update - version 3.3.2. (Yet the file itself is not found in the package)
