### ISSUE TITLE
Fileupload: images not shown in list view

### ISSUE THREAD

**Issue by jaanusnurmoja** [Fabrik/fabrik#1606]
When a fileupload element is set to show images in list view, images are no longer shown there. If a default image is set then this is always displayed, included when a real image is uploaded.

**Comment by britzke** [comment]
This is when you change the fileupload element to use thumbnails and some images are already uploaded before. Since you changed it, the thumbnail is rendered in the list but for the images which are uploaded before, no thumbnail has been created. So there is no image shown in the list.
if you would change it back to "no thumbnail", the images would be displayed again. If you want to use thumbnails then you can upload every image again which has been uploaded before. Then the thumbnails are created and displayed.

**Comment by jaanusnurmoja** [comment]
this issue seems to be fixed for now :)
