### ISSUE TITLE
Tabs not working in home of Fabrik admin component

### ISSUE THREAD

**Issue by agilare** [Fabrik/fabrik#1662]
On the right, all content is shown by default (About, news, etc.) piled up instead of being in panels
![fabrik_home_tabs](https://cloud.githubusercontent.com/assets/8960215/13779288/8b8945fa-eaba-11e5-89f1-7abe8e409cf9.jpg)

**Comment by trob** [comment]
Can you please post in the forums and mention exact versions?
GitHub issues are for confirmed recent issues.

This one I can confirm - but only if the backend is in French. It's a malformed French language string.
Fixed with https://github.com/Fabrik/fabrik/commit/66384ec56696fe6f9d84bdf421d0819fdf32f22c
