### ISSUE TITLE
Fabrik 3.9 with Joomla 3.9 PHP Fatal Errors

### ISSUE THREAD

**Issue by simbus82** [Fabrik/fabrik#2073]
Joomla 3.9
Fabrik 3.9
PHP 7.2

First error is:
Error 500 when try to install Fabrik Mailchimp Plugin

Second error is:
Website white page!
Caused by:
`PHP Fatal error:  require_once(): Failed opening required '/home/mysite/public_html/plugins/fabrik_element/captcha/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/mysite/public_html/plugins/fabrik_element/captcha/captcha.php on line 16.`

Solved after unpublishing Fabrik Captcha Plugin.

Thanks!

**Comment by cheesegrits** [comment]
Ooops, forgot to add the composer lib to the install XML

Fixed in:

https://github.com/Fabrik/fabrik/commit/e3570c03308a85784e9d5974cfdb9ba68451f63d
https://github.com/Fabrik/fabrik/commit/9ef9c7092d0495b23a59037420d403a13a661c1e

I'm running the build again, which will rebuild and upload the fixed plugin ZIPs.  By the time you read this they should be on the download server.

You can either do a github update, which will add those files, or you can grab the install ZIPs again.

**Comment by simbus82** [comment]
I have try the download from fabrikar website, but i obtain same errors... :-(
