### ISSUE TITLE
Is the project dead ?

### ISSUE THREAD

**Issue by mithubindia** [Fabrik/fabrik#2262]
Fabrik and Joomla --- both made for each other.
Fantastic project.  
But nothing coming out for Joomla 4.
Whether the project is dead ?

**Comment by Sophist-UK** [comment]
I tried to discuss how Fabrik could get a new lease of life with the CEO at Media A-Team several years ago, because it was clear to me that it would not survive with the limited resources they could put onto it and it needed a different more community oriented approach. But she was simply not interested in discussing it.

Take a look at just how long some PRs have been open and waiting for review (dating back to 2013!!!!!!!!!) to see that Fabrik has stagnated for several years.

I doubt that a J4 version will ever see the light of day. My advice for the past several years has been to avoid Fabrik for anything complex or mission critical. Now that J4 is production ready and J3 is effectively end-of-life, I would not recommend Fabrik to anyone.

As an alternative I would suggest looking a Joomla Component Builder. It has a far steeper learning curve but is IMO a more productive environment and one which has a future.

P.S. The [Fabrikar.com Forums](http://fabrikar.com/forums/index.php) are the better place to ask such questions.

**Comment by mithubindia** [comment]
Thanks for the feedback.
Alas, Fabrik could have worked on J4.
Joomla Component Builder is not my cup of tea.
Could you please point some other resource as versatile as Fabrik ?

**Comment by Sophist-UK** [comment]
@mithubindia Sorry - but no. After I decided that Fabrik had no future and was unsuitable for my needs I researched it widely and there is nothing comparable. The closest was JCB.

**Comment by Sophist-UK** [comment]
If there was ever solid evidence that this project is dead it is that there has not been a rebuttal from Media A-Team,

Hello??? Is anyone there????

**Comment by mediaateam** [comment]
Hello, as we've stated in other places, we are working on plans for the future of Fabrik currently with some different parties and will be making an announcement about it at the end of Q1 2022. Stay tuned and watch the site at that time for news.

**Comment by nbradshaw45** [comment]
I don't understand why mediateam can't provide some level of updates to the community on the fabrikar.com site regarding the future of fabrik. Even if you don't have all of the answers - being visible and giving some kind of updates would let the community know that it is at least being worked on - and it is NOT completely dead. OR - if it is dead - let people know - so that all of the people that have used this project can take their time and migrate accordingly...

**Comment by Sophist-UK** [comment]
It is heartening to know that Media A-Team are trying to resurrect this project, however my experience is that they haven't got any real understanding of how open source works or how to engage the community. They have spent several years treating this project largely as a proprietary code-base for us in their own projects. You only need to look at the list of 126 open PRs some of which date back to 2013 (of which 38 are mine) to know that the community has largely been ignored for the last 9 years ever since Media A-Team bought the copyright from Rob Clayburn.

I spent a lot of time trying to engage with the Media A-Team CEO to suggest how by engaging better with the Fabrik Community they could build a community spirit and delegate some responsibilities to the community in order to allow them to focus on their own priorities and the core development e.g. of a Joomla 4 version of Fabrik, but I was unable to get her to listen.

I do have some sympathies for Media A-Team who have their own business to run, however my experience suggests that they are particularly closed minded, unwilling to even consider how a partnership with the community could be beneficial to both groups.

In the end, having identified a lack of functionality I needed in several years, and coded enhancements submitted as PRs which then were never even reviews by Media A-Team, I decided that I couldn't update my code base if the PRs were not merged and I walked away from Fabrik for a few years, junking the code I had already developed. I then came back to it for a specific project, submitted a bunch more enhancements as PRs but found that nothing had changed and the community was, if anything, even more ignored - and so I walked away again and junked my development again.

So, when I read the above comment from Media A-Team, I interpret it to mean that they have decided that it is uneconomic even for them and are now either trying to flog it to someone else or just share the costs of maintaining it as a proprietary tool. What is clear from this comment is that the idea of engaging with the community to see if there was a way to keep it alive as a shared project is (still even now) not an idea that has even crossed their mind. IMO this does not bode well for the future of Fabrik.

My advice - take a look at Joomla Component Builder. It has a much steeper learning curve than Fabrik (it is more of a developer's toolkit than a web-interface way of building SQL tables and forms - more targeted at programmers than end users wanting a very simple way to create table and forms). But I always found Fabrik's user interface to be extremely laborious to navigate for anything of medium to high complexity, with no way to get an overview what you have created to compare e.,g. the security settings on one field with those of another and no way to e.g. bulk apply security settings to all fields. By comparison, once you have scaled the learning curve JCB can be a much more productive development environment.

**Comment by nbradshaw45** [comment]
Agreed [Sophist-UK] - I have been around since the early days of this project - and I definitely recognize you...I am hopeful that the project can stay alive.

**Media-A-Team** - I know you have gotten a TON of suggestions...but how about one more:

Send an email out to the community - ask them this question: "Would you pay $99/year for a license for this software if development continues?" See how many people respond to "YES" - then see if it would make sense to pay for a developer for this software. As far as support - DON'T provided code support for free - allow the community to provide that kind of support, or have a quote system for any code support - and allow the community to BID on that work.

I think this software is REALLY good for what it does - and I think you may have a good business model if you look at all of your options.

**Comment by Sophist-UK** [comment]
My previous suggestion was more of an honour one. 

Because the code is licensed under GPL, charging a license for the code is not legal. 

However, I previously suggested to Media A-Team an honour system whereby:

1. commercial developers using salaried staff should donate an amount of 1% of the staff salaries to Media A-Team in order to fund day-to-day support answering how-to questions and as a contribution towards ensuring that the investment in undertaking the development is protected by the software being maintained and updated.

2. development of a commercial system by unpaid individuals (i.e. an individual develops the software for e-commerce etc.), then they donate 1% of the revenue generated to Media A-Team for the same day-to-day support and longevity protection. If such users want support during development, then they would need to sign a contract committing to such payments in order to access it.

3. Media A-Team stop providing day-to-day support (i.e. how do I do X) to people / organisations who are not paying for support, and instead rely on the community to support each other.

4. Similarly, responsibility for the Wiki should be left to the community.

5. In return, then Media A-Team would give decent support to community generated enhancements to the code-base and not leave PRs to fester for the best part of a decade.

This seemed to me to be a reasonable compromise with benefits on all sides - a reasonable level of donations for commercial use that would help fund the Media A-Team support staff, and a quid-pro-quo for the community getting better support for PRs in return for taking support workload off the Media A-Team shoulders.

But Media A-Team were simply not prepared to even to listen to such suggestions, appearing to believe instead that we were out to take "their" software away from them.

And now they are undertaking discussions (of an unknown nature) with third parties (also unknown) without asking for the views of the community and indeed without being prepared to even share what their plans are.

IMO this does not bode well.

**Comment by nbradshaw45** [comment]
Very good suggestions Sophist...I just wonder if the license could be changed for a new J!4 version - so that starting with J!4 - it operates under a new license...but who knows.

On a side note - if I could reach out to you and ask more about JCB...I think JCB allows import/export projects...would be great if I could get a "starter" JCB import (Fabrik like setup) so that I could have something to start with.

**Comment by Sophist-UK** [comment]
Actually, I think it is (intentionally) pretty difficult to convert from a GPL license to anything more restrictive.

But more importantly, even if it were legal I would see a move to a commercial license as being a further retrograde step away from any community version being available and supported.

**Comment by mennoswaak** [comment]
JCB... I'm hesitating because of the steep learning curve. Went looking for some other component builder and found JDeveloper (stopped years ago), Component Architect (also stopping) and two more that I still need to investigate more: Component Creator and Component Generator (J3 and J4).  I  hope there is some one around that already has some experience with one or both, so I can save some time.

**Comment by mithubindia** [comment]
Let Media-A-Team decide its course of action. 
We all should wait till 31st March, 2022 ( End date for 1st Quarter of 2022)
Why can't we all put efforts in forking the project and make it compatible with Joomla 4.
Forking a project is not a crime after all.

**Comment by Sophist-UK** [comment]
To respond to @mithubindia 's latest comments:

> Let Media-A-Team decide its course of action. We all should wait till 31st March, 2022 ( End date for 1st Quarter of 2022)

There is no choice in this. Media A-Team are going to do what they are going to do without any consideration of community opinion - it is happening regardless. So a bit of a pointless comment, really. 31 March is literally **tomorrow** - but personally I don't expect anything tomorrow or the next day or perhaps even ever. And if there is an announcement, I have major doubts that it will be anything that the community actually wants to hear or is in our benefit. Media A-Team have shown no interest in the community before, being solely concerned with their own benefit, and there is no reason whatsoever to expect this to be any different this time around. But perhaps we will be pleasantly surprised.

> Why can't we all put efforts in forking the project and make it compatible with Joomla 4. Forking a project is not a crime after all.

Forking the repo takes no effort. Most people reading this will have already forked the repo. Creating an alternative project from a forked repo is a completely different undertaking. The GPL makes this completely and entirely legal to make a fork publicly available as an alternative source and to modify it as you see fit - but whilst it is completely legal and easy to do so, the practicalities of running a competing project are much more difficult.

When I suggested to Media A-Team that I was thinking of forking the project (because they were treating the community so badly), they got most upset and started claiming copyright at me (which of course is rubbish because the code is GPL) - but this does support my belief that Media A-Team do not understand open source and treat the code as proprietary.

1. There are some big long-term difficulties in maintaining a fork when the original repo is also being maintained. Eventually the source code will diverge sufficiently that many changes made by Media A-Team will not merge automatically and will need to be manually retrofitted, so there needs to be a big commitment. I had a fork with big changes, and it simply became impractical for me to maintain it when my changes were not being merged back into the Media A-Team source - and that is why I quit using it.
2. Whilst the source code is GPL, the wiki is not and is probably default copyright Media A-Team. That said, I wrote a lot of the wiki, and I would be happy to claim copyright on anything I wrote in order that it can be used elsewhere.
3. If you decide to fork the project, please feel free to copy the code from my open PRs to integrate in - there is some genuinely useful stuff there.
4. If you are genuine about forking this project, then you will need to get the community together and discuss how this would work - how would the new project be led, how would you create long-term continuity as the community changed, who would set direction, how would essential costs be funded, how would you find the seriously capable technical support needed etc. **This is a non-trivial undertaking, so please don't underestimate the commitment needed.** 
5. Getting in touch with the community in order to get them together is itself a non-trivial exercise, and one which you might well consider as an example of the difficulties you will face.

Whilst I am no longer using Fabrik and so not currently interested in participating in a fork (though I might be persuaded to pick up an abandoned project and start using it again if this happens), if you are serious about forking this project then please make contact with me elsewhere so we can discuss the practicalities.

**Comment by mediaateam** [comment]
Please see the posting on the website - https://fabrikar.com/blog/89-the-future-of-fabrik

**Comment by Sophist-UK** [comment]
To summarise [The Future of Fabrik](https://fabrikar.com/blog/89-the-future-of-fabrik) link posted above and to answer the question posed by subject line of this issue "Is the project dead":

### Yes - the project is dead.

Looking back at my email archives, I found the original press release when Media A-Team took over Fabrik in June 2016, and they promised:

> In case you missed the press release that was distributed today, we are excited to announce that Media A-Team will be stepping into the management role for the day-to-day operations of the Fabrik open source project. We have been long time user and supporters of Fabrik and are excited for this opportunity to take the project forward by adding more hands on deck.
>
> Hugh Messenger will still be a full-time Fabrik guru, and Rob Clayburn, the original project developer, will still be connected to the project in a consultant and developer role. Also, the much appreciated core of Fabrik contributors are still making commits everyday.
>
> In the near future we will be rolling out a fresh new look and have many goals for the future of Fabrik, such as enhanced support, more robust documentation and tutorials, and professional plugins. We also plan on being more visible at Joomla! and PHP events, so stop by and say hi if you see us in the community.

As far as I am aware, Rob Clayburn did not continue to be involved in a developer role (and contributing 2 very small changes in 2017 IMO is not sufficient to justify such a claim), Media A-Team did not (as they promised) appreciate the core Fabrik contributors (because PRs were not reviewed or merged), did not role out a fresh new look (unless you consider that a change of colours on the Forum meets that), didn't provide enhanced support or more robust documentation or new tutorials or professional plugins. They were not, as far as I am aware, ever "more visible at Joomla or PHP events", but instead let Fabrik fall off the Jooma Extensions Directory (not sure when, but it was a long time ago - I believe due to integrating an insecure version of a PDF generator) and never remediated this to get it back into the directory.

You will have to draw your own conclusions as to whether Robbie Adair genuinely had the intentions stated but found that she had bitten off more than she could chew, or whether she only ever wanted to support Fabrik for Media A-Team internal use and the PR was hyperbole, but either way IMO the promises she made were never fulfilled in even the smallest of ways.

I believed the project was effectively dead several years ago, and sadly I believe that this is now proven to be true. I tried to engage with Robbie to suggest an alternative economic approach which was more community oriented and would have resulted in increased revenues and a greater ability to invest - but she was not the slightest bit interested.

So I see this latest press release only as an official notification that the project is indeed now dead.

To quote from the latest press release:

> We have been talking to many companies, mainly Joomla extension development companies, looking for the right team to take over the project and continue the Fabrik 4 for J4 rebuild. Unfortunately, we have had no luck yet, most Joomla companies are struggling to get their own extensions to Joomla and are hard pressed to spend money or resources on anymore Joomla development.

Should we be surprised? 

As a result of Media A-Teams failure to deliver on their promises, the extension is no longer listed in the Extensions Directory, has significant technical debt to resolve before it can get its listing back, will need a massive effort to get it working with Fabrik 4, and has no developers who understand the internals. There is little or nothing that Media A-Team can offer any other extension developers that is worth anything - but I have no doubt that Media A-Teams efforts are based entirely on trying to find someone who will pay for the copyright ownership and NOT on how to keep the project alive, since even now they are **NOT** making **any** efforts to engage with the community of users. 

**In short, IMO Media A-Team have been bad custodians of this project in the 5 3/4 years they have been responsible for it. They have driven this software into the ground.**

Despite Media A-Team's initial promises, supporting Fabrik has been thrust onto the sole shoulders of Hugh / @cheesegrits - Hugh has tried his best but I am not surprised in the circumstances that "he is burned out and simply not interested in working on Fabrik any more, preferring to focus on new technology stacks."

### I would like to say a public "thank you" to Hugh for all his efforts over the many years.

Even now, if Media A-Team genuine wanted to keep the project alive they could start to engage properly with the community, could offer to make the project a community-only project, form a formal or informal "foundation" to oversee the project and create a governance structure, could offer to underwrite the hosting of the web site in the event that donations for essential costs couldn't cover that. But AFAIK, such a thought has never crossed their minds, so please exercise some critical judgement when considering whether Media A-Team are genuinely interested in the future of Fabrik,

Finally a few blunt comments on Media A-Teams recent press release:

1. "Fabrik is and always has been open source." Media A-Team made it clear to me that they do not understand open-source when they threatened me with Copyright legalities contrary to the Fabrik GPL license. Unimpressive. Furthermore, the long, long, long list of unreviewed and unmerged PRs can genuinely only be considered them giving the finger to both open source and the user community.

2.  "So, anyone is free to fork the project, and we have always encouraged people to do so, and they have over 400 times." There are two types of forking. The first type is where you clone the repo so that you have a personal copy for your own use, so you can adjust the code and perhaps submit PRs back to the main repo. This has indeed happened 416 times, and Media A-Team may indeed have actively encouraged people to do this - certainly I cannot recall any instances of them discouraging it. The second type is where a developer or a community takes such a copy and maintains / enhances it and makes it available for others to use as a supported offering. When I suggested that I was thinking of doing this, the Media A-Team response was the absolute opposite of "encouraging". This part of their statement is simply a lie - they have **NOT** "always encouraged people to do so".

3. "We don't have a large community" - They had a significantly larger community in 2016 when they took over responsibility for Fabrik - the number and scope of code contributions since then has declined massively under their watch. "but we do have a great community" - what hypocrisy, since they have shown so little interest in engaging with this "great community" over the future of a project that they have effectively run into the ground.

4. "Regardless, we will keep the project supported for J3 until it is end of life in August 2023." Support in what way? They will not have any knowledgeable developer who can provide actual code support. Consequently I am presuming that this means keeping the web site and forums etc. alive, but they have not been explicit about this and even if they had I am not convinced that they can be relied upon to keep such a promise. My personal opinion is that this is a statement that they need to support the commercial web sites they have delivered on Fabrik whilst they remain alive, and presumably plan to redevelop them for their clients using different technologies before August 2023.

### If Media A-Team is reading this and would like to engage with the community, it is still not too late.

All they would need to do is to indicate that they would be happy for the community to use the Forums for us to discuss amongst ourselves how it might be possible to keep it alive, and then see whether anything sensible arises out of such discussions. 

The alternative would be for the Community to do what Media A-Team say they have "always encouraged people to do" and fork the project to create a whole new project and go it alone without any support from Media A-Team. The wiki and support forums are probably not covered by the code GPL so if Media A-Team were genuinely encouraging people to fork the project and keep it alive, and genuinely supportive of open source, then perhaps they would be willing to commit to placing these resources in the public domain. But worst case scenario is that these would be lost (making a poor documentation situation even worse). That said, IMO **going it alone would be worse for both the community and Media A-Team than a joint effort**, but given sufficient interest then I think this would be possible.

**Comment by Sophist-UK** [comment]
P.S. Closing this issue is IMO yet another example of Media A-Team's fantasy thinking. The issue of whether Fabrik can be resurrected is not closed. 

@mithubindia As the originator of this issue, are you able to reopen it?

**Comment by cheesegrits** [comment]
I need to be absolutely crystal clear on this.  The reason I walked away from actively developing Fabrik was because of you, @Sophist-UK.  Nobody and nothing else.  Just you.

Within months of your involvement, I went from enjoying every day on the project, waking up looking forward to the challenges, to dreading it.  Waking up to full blown panic attacks, struggling to draw a breath, with a chest so tight it felt like a heart attack.  Breaking out in massive bloody swathes of stress induced eczema on the backs of my legs, to the point the only way I could work was by wrapping my legs in gauze soaked in topical steroids.  All of that stopped literally overnight, the day I decided I just couldn't be involved with anything you were involved with.  So I stepped back to just fixing bugs in the background, and adding features I needed for our own agency work.

Your toxic, obnoxious, arrogant, confrontational personality is a death knell for any open source project.

I'm happy to help with consultancy on any community effort to move Fabrik to J4, as a resource to be called on for any particularly intractable issues that need my kind of in depth knowledge of the code ... unless Sophist is involved.  In which case I want nothing to do with it. 

And just to clear up something else.  Fabrik would have died back when Rob moved on, if Robbie hadn't stepped up.  I was in the process of shutting the whole thing down, as the revenue had dropped to the point it didn't even cover my rent, let alone earn a living.  She single handedly kept Fabrik alive by pouring six figures into it over the first couple of years, paying me full time to maintain it, paying the hosting fees, etc.  But a combination of Sophist and J4 killed us.

The moving goalposts of the J4 APIs during the alpha and early beta phases wasted 6 months of full time work.  And now that I've moved on to modern stack development (PHP 8.1, React / React Native, Laravel, Vue, Livewire, etc.), without me to do the work, there simply isn't anyone else.  Not even for hire.  There just is not anyone with the depth and breadth of J! / Fabrik knowledge and skills required, who also wants to spend a year doing it.  Although as I said, if there is a community effort, with enough skilled people to do the work who want to move it to J4, I'm happy to act in a consultancy role.  Unless of course Sophist is involved.

**Comment by lousyfool** [comment]
Thank you so much, @cheesegrits.

**Comment by Sophist-UK** [comment]
@cheesegrits - Well, you can blame me all you like, but (whilst it was never my intention to cause you additional stress) my considering forking the project a few years ago was a direct response to the a situation where support for the community was already practically non-existent and to a company that was completely indifferent to the community and who wouldn't engage or even consider an alternative approach that would potentially have benefitted everyone. I wanted to work **WITH** Media A-Team and you, but Robbie was not interested. 

You only need to look at the dates of the open PRs to see that the lack of community support goes back a lot further than 2018. Of the open PRs, 27 date from 2013-2016 before Media A-Team (7 per year), and 86 date from 2016-2018 after Media A-Team took over (43 per year, an increase of 500%). Yes - some of the open PRs are mine (32), but the other open 94 PRs are by others users, some from other long-standing and respected members like @jaanusnurmoja (22). **Each of these PRs represents hours of effort by community members to help improve Fabrik, and for Media A-Team to simply ignore them clearly goes against Robbie's assertion that she values community contributions.** These PRs also represent the community helping to fix real live problems in Fabrik that are impacting their own development efforts, and when they are not merged, indeed not even reviewed, that eventually makes these development projects impossible to update. Media A-Team was already refusing much needed help from the community. I do not blame you personally, Hugh - before Media A-Team there were two of you supporting Fabrik - after 2016 there was just you, so resources were already stretched further. 

In 2016 Robbie promised that she would resource Fabrik properly. After 2 years, it was clear that this was not the case (probably because of the economics), and I could see that the Media A-Team's economic model was not working, particularly with the huge effort required to create a J4 version, the community was being largely ignored, and that if it didn't change then eventually it was going to become impossible for Media A-Team to continue. I wanted to work **with** Media A-Team and made supportive suggestions to see if an alternative approach would create better funding. But Media A-Team was unwilling even to listen, much less seriously consider alternatives.

It was only after Robbie rebuffed these, that I considered whether a project fork was an alternative possibility. A project fork is not unknown in the Open Source world - e.g. LibreOffice from OpenOffice, SuperSlicer from Prusa Slicer from Slic3r. It is a fundamental aspect of Open Source that this is a possibility if a community feels that such a thing is beneficial. So it wasn't personal, even if you did take it as such.

I **never** considered the situation to be a direct reflection on you and never made it personal. I accept that you took it personally even though it was not intended as such, and I very much regret that this happened and apologised to you at the time. But I haven't had any involvement in Fabrik for over 3 1/2 years - so please don't try to suggest that this is all down to me and that I single-handedly sank this project.

Even now, I am suggesting that this could still be a joint effort between Media A-Team and the community. Robbie has had every opportunity to engage with the community to find a future for Fabrik - but she refused to do so 3.5 years ago and refused to do so when she finally decided that it wasn't working, and even now at the final curtain she is **still** unwilling to engage with the community. You cannot lay that blame on me - that is entirely down to Robbie.

**Comment by skurvish** [comment]
OK, so, I cannot migrate my site to J4 without Fabrik. If I have to do that I will have to cripple the site so much that it would be worthless. There are a number of us here who have coding skills and have done work on Fabrik. Can we put together a core group of us and fork the repo and figure out what needs to be done to get it working in J4?

Who is up for doing this?

**Comment by Sophist-UK** [comment]
It is certainly possible to fork the project and do a one off effort to produce a J4 version, but if you look back you will see that every time a new Joomla version was announced, there was a matching Fabrik update needed to make it work. So this cannot be a one-off effort, but instead would need to be an ongoing community effort.

Whilst a one-off effort could just be a group of enthusiasts getting together to do it, an on-going project would need a bit more in  the way of governance - to decide on a strategy and priorities and to handle all the other issues associated with supporting a new project (like documentation, and support).

But my advice first off is to see whether it is possible to come to some arrangement with Media A-Team - rather than immediately adopting a go-it-alone approach. 

Media A-Team may well be the largest single existing user of Fabrik (with more legacy sites than anyone else that would benefit from J4 support) and so may actually more to gain than anyone from a community-led revival, and I would hope that they might be persuaded to see the benefit of cooperation rather than forcing the community to go-it-alone.

That said, their attitude to date does not suggest that they care a jot - and so far at least they have not responded to my suggestions here any more than they did 3.5 years ago.

**Comment by skurvish** [comment]
Sorry, I guess I did not explain myself completely. I was intending it to be an ongoing project with a core team of community developers working together to get a J4 version operational. It might be possible to create a forum/support structure much like has been suggested before, to provide some funding but that can come after. Many of us have a vested interest in seeing Fabrik run on J4. If Media A-team is not going to do it then I think we have to.

If we can get a core group together maybe we can set up an invitation only discussion portal (Google groups or similar) to hash out some of the details. We may end up deciding we cannot do it but we should spend some time to look into it before throwing up out hands.

**Comment by HyperOsmar** [comment]
@escroto 
I'm not a developer, but I've been a Fabrik user since its first versions.
If my experience as a user helps to contribute to the community, you can count on me...

**Comment by saman222** [comment]
@Sophist-UK 
If it is possible come to Telegram such as JCB developers groups... I also like to commite for J4 if i can. I have some commit on JCB. We need hugh help certainly...

**Comment by mediaateam** [comment]
Just a final update on this issue, we have a small group of developers in the community we are discussing a possible way to move forward. Because, regardless of what someone who has not been in the community for years claimed, we do communicate with the community, and have an active private channel with some of our long term users. 

So, please read the forum post and contact us if you are interested in participating in the meeting we will be setting up - https://fabrikar.com/forums/index.php?threads/the-future-of-fabrik.53337/

Also, please note that any of you are more than welcome and encouraged to fork Fabrik and have a go at the J4 migration with any group you want, it's open source, that is what the GPL is all about. I, regardless of accusations, have never discouraged the project from being forked. I am, and always have been, a huge advocate of open source. I've spent a ton of money, time, and sweat on open source projects over the years. Not being a developer, I pay developers, I travel on my own dime to speak about projects and bring awareness, and I spend volunteer time helping to organize events that help push open source projects forward. No one is perfect, I'm sure I could do things better, but I'm just human, and I'm doing the best I can. And, I encourage you all to find ways to contribute to open source projects, though exhausting at times, it's a rewarding endeavor.

As GitHub issues really should be bugs reports and such, hence why this issue was closed before, not because of any nefarious reasons as accused, this issue will be closed after this post. We encourage you to instead move this discussion to the forum post linked above.

Lastly, @Sophist-UK - I realize that I must have hurt your feelings in the past when I had to ask you to leave the community, but I couldn't ignore the amount of complaints I was receiving about the toxicity you were spreading on the forum and in the community. I am sorry that you are obviously still very upset towards me personally, but please know that I do hope you have found a new community and product that makes you happy, and that you can have a positive experience within.

**Comment by Sophist-UK** [comment]
I think we should all welcome a willingness by Media A-Team finally to engage with the community, or at least a subset of it. I see no reason why this discussion shouldn't be held in a Fabrikar forum instead.

Given the animosity between myself and Hugh/Robbie I would not wish to be a negative influence on any discussions, so I will not be attempting to join this discussion and will leave this to others.

However, I do urge caution about any deal done in private with a small select group of developers rather than something agreed in a public forum as would be normal in the open source world.

**Comment by Sophist-UK** [comment]
I stand corrected. There is a good reason that discussions should not be undertaken on the Fabrikar Forums in the post linked to above - because Media A-Team have decided to be selective about who they allow to post there - specifically I am not allowed to post there. I am not talking about the private discussion group mentioned in the above forum which is even more selective, I am talking about the post itself.

As I previously said, I do not wish to be a disruptive influence on what I hope will be positive discussions, so I am not personally bothered about being excluded, however I do think that unilateral decisions by Media A-Team on who should and should not be included in discussions about the future of Fabrik are not a good indicator.

Whilst I recognise the truth in Robbie's assertion that anyone can "fork Fabrik and have a go at the J4 migration", personally I do not believe that having multiple competing efforts at achieving a J4 migration would be the best use of the limited resources available to work on Fabrik. And if multiple attempts to achieve this are successful, I do not believe that the resulting fragmentation of the Fabrik community supporting (likely) incompatible versions of Fabrilk would be a good thing either. And this is why I think that private discussions with selected Fabrik users is a bad thing - IMO open discussions in which all parts of the community can take part would be the best chance of achieving a solution in which major users get more say but where smaller users can also have their say.

However, I would like to apologise if my criticisms of Robbie appeared one sided. Whilst I stand by what I have said (because they are factually based), Robbie did step in in 2016 when Fabrik would otherwise have foundered (as Hugh said) and she did keep it alive. Running any small business is a challenge, even more so through a pandemic, and I am sure that she has put as much time and money into it as she could. It was clear that support was still struggling from a lack of resources long before the pandemic and that a J4 version would be a challenge. I can quite understand that the pandemic just made this worse. I can also understand that she needed to focus the resources that she was paying for on changes that were beneficial to her - that is entirely rational and reasonable, but that is NOT the same as supporting open source or supporting the Fabrik community.

That said, Robbie is again being highly selective about her statements about me and my involvement. 

You only need to review the Forums, the Wiki and Github to see how much contribution I made to Fabrik and the community both prior to Media A-Team's involvement and for a couple of years subsequently. At the time my contributions on the forums were valued - I was definitely in Media A-Teams good books for a few years. I am not sure how long the "active private channel with some of our long term users" has existed, but even when I was in their good books I was never invited, so presumably this is something more recent. 

My first approaches to Media A-Team with suggestions of an alternative economic model that might benefit everyone were made privately as I have always felt that a single community would be the best approach - but these were simply ignored. Not underestimating the effort required to fork a project to provide a better support to the community for their enhancements, I approached other members of the community privately to see whether they would be interested in forming a group to fork the project. And this is what Robbie objected to - an attempt to discuss forking the project with other users and the idea of forking the project. I cannot find the or emails with Robbie's response, but my recollection (which could be wrong) is that she claimed that I was trying to void her copyright in the software. I had/have never suggested misusing anyone's copyright, so I have to assume that she was objecting to the idea of forking the project (contrary to her more recent statements). I will, however, readily accept that approaching fabrik users privately to see whether there was interest in a project fork was a negative reflection on Media A-Team and created ill-will - and perhaps with hindsight I could have done this in a differently way that created less ill-will - but then again which of us is perfect, and if we reflect we can all point to things that we could potentially have done better.

However my original approach was to do get a ball rolling privately with Media A-Team, and it was **only** after this was ignored that I felt that a project fork was an alternative to consider. I still have no idea why Robbie refused to even discuss my ideas with me - they were suggestions and not demands, they were designed to be equally beneficial to Media A-Team and the community, they were designed to bring people together. (I still have the email - and I would be happy to post it here if anyone is interested - but from memory the gist is as summarised above.) But having tried (over several months if memory serves me) to get Media A-Team at least to consider an alternative approach, my attempts to see whether there was support for a project fork that Robbie and Hugh consider "toxic" were **only** a consequence of the indifference from Robbie.

At that point, I could have made broader efforts to fork the project despite Robbie's objections, but instead I decided to walk away and not create more waves. For several years I have said little to nothing anywhere about Fabrik, allowing Media A-Team to provide the best support they could. I have not subsequently abused my membership of the forums by making ongoing negative comments or unwarranted personal accusations. Robbie did NOT as she said "ask me to leave the community", and indeed this is literally the first such suggestion.

**Summary:** As I have said, I am not going to try to get involved with any discussions with Media A-Team, because the ill-will on their part would make my involvement disruptive. But I do urge the community to try to hold such discussions in public rather than in private, to get input from all parts of the Fabrik community, not just private interests, and to try to ensure that whatever deal that is thrashed out does not fragment the community and allows for the contributions of all users both large and small.

**Comment by Sophist-UK** [comment]
Correction to the above comment: The forum post mentioned in Robbie's last comment here is NOT one that anyone can comment on - it is an announcement only post. So by closing this issue, Robbie is effectively attempting to close down any public conversation in favour of an online discussion which is only going to be open to community members that Media A-Team select. **An invitation-only closed secret meeting cannot IMO be considered a community consultation.**

**Comment by Sophist-UK** [comment]
AFAIK, Media A-Team has NOT used either Github or their Forum mailing list to send an email to as many users of Fabrik as possible telling people about their secret meeting.

**How can the community as a whole be considered represented at a secret meeting when the invite list is entirely controlled by Media A-Team who have previously shown such scant regard for the community?**

This doesn't feel like community engagement - it feels like a stitch-up to preserve Media A-Team's interests over those of the community as a whole.
